name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Configure Git
      run: |
        git config --global user.name "Shuang-Zi"
        git config --global user.email "yang03_15@126.com"

    - name: Bump version and update lock file
      run: |
        npm version patch -m "Upgrade to %s for automated release"
        npm install
        git add package-lock.json
        git commit --amend --no-edit
        git push origin main --tags

    - name: Build project
      run: npm run build

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}